### PR TITLE
Make the Docker images produced support `arm64`

### PR DESCRIPTION
**Pull request by jsf9k**
Make the Docker images produced support the `arm64` platform.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Fingers crossed it works!

**Comment by jsf9k** [comment]
> Fingers crossed it works!

Bold.  I like it.

**Comment by geerlingguy** [comment]
@jsf9k - Heh, unfortunately for some reason the build hangs on arm64 on this container build too. I wonder if GitHub Actions has a weird problem with arm64 cross-builds using BuildX? See older issue too, but probably not related: https://github.com/docker/setup-qemu-action/issues/42

**Comment by jsf9k** [comment]
Where do you see that it hung up?  It [looks like it succeeded](https://github.com/geerlingguy/docker-fedora40-ansible/actions/runs/8854243324/job/24316933804).

**Comment by geerlingguy** [comment]
lol oops! Re-re-merged.

**Comment by jsf9k** [comment]
> lol oops! Re-re-merged.

Sounds like your Friday is going about like mine is :laughing:

**Comment by geerlingguy** [comment]
Haha, all the crazy things started happening after 4pm, too.

**Pull request merged**
